# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

before_script:
 - npm install

stages:
 - build

build:lint:
  stage: build
  script:
    - npm run lint


build:test:
  stage: build
  script:
    - npm test

# Publish tagged versions to npm
#publish:
#  stage: deploy
#  only:
#    - tags
#    - triggers
#  script:
#    - npm run build
#    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
#    - npm publish